name: Manual Database Seeding

on:
  workflow_dispatch:
    inputs:
      project_id:
        description: 'Google Cloud Project ID'
        required: true
        default: 'lean-ehr'
      region:
        description: 'Google Cloud Region'
        required: true
        default: 'europe-west1'
      job_name:
        description: 'Cloud Run Job Name'
        required: true
        default: 'lean-ehr-data-upload'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/31765765651/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'assisted-living-app@lean-ehr.iam.gserviceaccount.com'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Fetch KMS Configuration
        id: kms_config
        run: |
          KMS_LOCATION="europe-west1"
          KEYRING_NAME=$(gcloud kms keyrings list --location=$KMS_LOCATION --project=${{ github.event.inputs.project_id }} --filter="name:assisted-living" --format="value(name)")
          echo "KMS_KEY_RING=$KEYRING_NAME" >> $GITHUB_ENV
          echo "KEK_GENERAL_PATH=$(gcloud kms keys list --keyring=$KEYRING_NAME --location=$KMS_LOCATION --project=${{ github.event.inputs.project_id }} --filter='name:kek-general' --format='value(name)')" >> $GITHUB_ENV
          echo "KEK_CONTACT_PATH=$(gcloud kms keys list --keyring=$KEYRING_NAME --location=$KMS_LOCATION --project=${{ github.event.inputs.project_id }} --filter='name:kek-contact' --format='value(name)')" >> $GITHUB_ENV
          echo "KEK_CLINICAL_PATH=$(gcloud kms keys list --keyring=$KEYRING_NAME --location=$KMS_LOCATION --project=${{ github.event.inputs.project_id }} --filter='name:kek-clinical' --format='value(name)')" >> $GITHUB_ENV
          echo "KEK_FINANCIAL_PATH=$(gcloud kms keys list --keyring=$KEYRING_NAME --location=$KMS_LOCATION --project=${{ github.event.inputs.project_id }} --filter='name:kek-financial' --format='value(name)')" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        id: build
        working-directory: ./packages/assisted-living
        run: |
          gcloud builds submit --tag "${{ github.event.inputs.region }}-docker.pkg.dev/${{ github.event.inputs.project_id }}/lean-ehr-repo/lean-ehr-uploader:latest" .

      - name: Deploy to Cloud Run Job
        run: |
          gcloud run jobs deploy ${{ github.event.inputs.job_name }} \
            --image "${{ github.event.inputs.region }}-docker.pkg.dev/${{ github.event.inputs.project_id }}/lean-ehr-repo/lean-ehr-uploader:latest" \
            --region "${{ github.event.inputs.region }}" \
            --project "${{ github.event.inputs.project_id }}" \
            --cpu 2 \
            --memory 8Gi \
            --task-timeout 10800 \
            --max-retries 0 \
            --set-env-vars="GCP_PROJECT_ID=${{ github.event.inputs.project_id }},KMS_LOCATION=europe-west1,KMS_KEY_RING=${{ env.KMS_KEY_RING }},KEK_GENERAL_PATH=${{ env.KEK_GENERAL_PATH }},KEK_CONTACT_PATH=${{ env.KEK_CONTACT_PATH }},KEK_CLINICAL_PATH=${{ env.KEK_CLINICAL_PATH }},KEK_FINANCIAL_PATH=${{ env.KEK_FINANCIAL_PATH }}"

      - name: Execute Cloud Run Job
        run: |
          gcloud run jobs execute ${{ github.event.inputs.job_name }} \
            --region "${{ github.event.inputs.region }}" \
            --project "${{ github.event.inputs.project_id }}"
